version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - my_network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - my_network
  
  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_MASTER: spark://spark-master:7077
      PROJECT_HOME: /home/ibdn/BDFI/practica_creativa/
    networks:
      - my_network
    volumes:
      - /home/ibdn/BDFI/practica_creativa/flight_prediction:/flight_prediction
      - /home/ibdn/BDFI/practica_creativa/models:/home/ibdn/BDFI/practica_creativa/models

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      SPARK_MASTER: spark://spark-master:7077
      PROJECT_HOME: /home/ibdn/BDFI/practica_creativa/
    networks:
      - my_network
    volumes:
      - /home/ibdn/BDFI/practica_creativa/flight_prediction:/flight_prediction
      - /home/ibdn/BDFI/practica_creativa/models:/home/ibdn/BDFI/practica_creativa/models

  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      SPARK_MASTER: spark://spark-master:7077
      PROJECT_HOME: /home/ibdn/BDFI/practica_creativa/
    networks:
      - my_network
    volumes:
      - /home/ibdn/BDFI/practica_creativa/flight_prediction:/flight_prediction
      - /home/ibdn/BDFI/practica_creativa/models:/home/ibdn/BDFI/practica_creativa/models

  spark-submit:
    image: bde2020/spark-submit
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    environment:
      SPARK_MASTER: spark://spark-master:7077
      PROJECT_HOME: /home/ibdn/BDFI/practica_creativa  
    volumes:
      - /home/ibdn/BDFI/practica_creativa/flight_prediction:/flight_prediction
      - /home/ibdn/BDFI/practica_creativa/models:/home/ibdn/BDFI/practica_creativa/models
    networks:
      - my_network
    command: >
      bash -c "sleep 15; /spark/bin/spark-submit --class es.upm.dit.ging.predictor.MakePrediction --master spark://spark-master:7077 --packages org.mongodb.spark:mongo-spark-connector_2.12:10.1.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 /flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar show"

  mongo:
    image: mongo:4.4.29
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - /home/ibdn/BDFI/practica_creativa/data:/home

  mongo-client:
    image: mongo:4.4.29
    container_name: mongo-client
    depends_on:
      - mongo
    networks:
      - my_network
    volumes:
      - /home/ibdn/BDFI/practica_creativa/data:/home
    command: > 
      bash -c " /home/import_distances.sh"

  flask:
    build: ./docker/flask
    container_name: flask
    depends_on:
      - kafka
      - mongo
    ports:
      - "5001:5001"
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongo:27017
      PROJECT_HOME: /home/ibdn/BDFI/practica_creativa/
    networks:
      - my_network
    volumes:
      - /home/ibdn/BDFI/practica_creativa:/home/ibdn/BDFI/practica_creativa
    command: bash -c "sleep 45; python3 /home/ibdn/BDFI/practica_creativa/resources/web/predict_flask.py"

networks:
  my_network:
    driver: bridge